---
title: "BayesianCognitiveModeling3"
output:
  rmdformats::downcute:
    highlight: kate
    css: mycss.css
    dev: "ragg_png"
date: "2024-05-29"
---
# 第三章 二項分布を使った推論

## 3.1 比率を推論する
  - 2章の例を使う
    - n=10, k=5（10回試行で5回成功の二項分布過程）

```{r}
library(rstan)

rstan_options(auto_write=TRUE)
options(mc.cores=parallel::detectCores())
rstan_options(auto_write = TRUE)


dat <- data.frame(5) #read.csv('dat1.csv')
colnames(dat)<-'tf'

nsample<-nrow(dat)
data_list<-list(k=dat$tf, N=10, n=nrow(dat))

mcmc_result<-stan(
  file='dat1.stan',
  data=data_list,
  seed=1,
  chains=2,
  iter=20000,
  warmup=1000,
  thin=1
)
print(mcmc_result, probs=c(0.025,0.5,0.975))
traceplot(mcmc_result)
stan_hist(mcmc_result)
stan_dens(mcmc_result)

```
## 3.2 2つの比率の差
- 2つの異なる成功率$\theta_1$と$\theta_2$, 当然異なる成功回数$k_1$と$k_2$。
  - その差$\delta=\theta_1-\theta_2$に関心がある
  - $K_1=5, k_2=7$, $n_1,n_2=10$として$\delta$を考えてみる
  
```{r}
library(rstan)

rstan_options(auto_write=TRUE)
options(mc.cores=parallel::detectCores())
rstan_options(auto_write = TRUE)


dat2 <- data.frame(t(c(5,7))) #read.csv('dat1.csv')
colnames(dat2)<-c('tf1','tf2')

nsample<-nrow(dat2)
data_list2<-list(k1=dat2$tf1, k2=dat2$tf2, n1=10, n2=10)

mcmc_result2<-stan(
  file='dat32.stan',
  data=data_list2,
  seed=1,
  chains=2,
  iter=20000,
  warmup=1000,
  thin=1
)
print(mcmc_result2, probs=c(0.025,0.5,0.975))
traceplot(mcmc_result2)
stan_hist(mcmc_result2)
stan_dens(mcmc_result2)

```

## 共通の比率を推論する

- nとkはさっきと同じで、ただし$\theta$は共通だと考える

```{r}
library(rstan)

rstan_options(auto_write=TRUE)
options(mc.cores=parallel::detectCores())
rstan_options(auto_write = TRUE)


dat3 <- data.frame(t(c(5,7))) #read.csv('dat1.csv')
colnames(dat3)<-c('tf1','tf2')

nsample<-nrow(dat3)
data_list3<-list(k1=dat3$tf1, k2=dat3$tf2, n1=10, n2=10)

mcmc_result3<-stan(
  file='dat33.stan',
  data=data_list3,
  seed=1,
  chains=2,
  iter=20000,
  warmup=1000,
  thin=1
)
print(mcmc_result3, probs=c(0.025,0.5,0.975))
traceplot(mcmc_result3)
stan_hist(mcmc_result3)
stan_dens(mcmc_result3)
```
## 事前と事後の予測

- 事前分布、事後分布
- 事前予測分布, 事後予測分布
- n=15, k=1という例で

```{r}
library(rstan)

rstan_options(auto_write=TRUE)
options(mc.cores=parallel::detectCores())
rstan_options(auto_write = TRUE)


dat4 <- data.frame(1) #read.csv('dat1.csv')
colnames(dat4)<-'tf1'
data_list4<-list(k=dat4$tf1, n=15)

mcmc_result4<-stan(
  file='dat34.stan',
  data=data_list4,
  seed=1,
  chains=2,
  iter=20000,
  warmup=1000,
  thin=1
)
print(mcmc_result4, probs=c(0.025,0.5,0.975))
#traceplot(mcmc_result4)
#stan_hist(mcmc_result4)
stan_dens(mcmc_result4)

priorpredk<-extract(mcmc_result4)$priorpredk
postpredk<-extract(mcmc_result4)$postpredk

barplot(table(priorpredk))
barplot(table(postpredk))

```

## 事後予測
2つの極端な事象(n1=10, k1=0, n2=10, k2=10)が同じ二項過程（1つの$\theta$から生じたと考えると、推定された$\theta$はデータと合わないよね、的な話。

## 同時分布
未知の変数が2種類ある場合。成功率$\theta$と総観測数$n$。